# Generated by Django 5.2.10 on 2026-05-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
