# Generated by Django 5.2.10 on 2026-05-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_auth', '0002_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('CANDIDATE', 'CANDIDATE'), ('VIEWER', 'VIEWER')], default='VIEWER', max_length=50),
        ),
    ]
